/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.drmc.rasd.view;

import java.nio.file.Path;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.drmc.rasd.controller.ModelMessageRecu;
import org.drmc.rasd.dao.DbConnection;
import org.drmc.rasd.dao.IDbConnection;
import org.drmc.rasd.dao.IMessageRecuDao;
import org.drmc.rasd.dao.MessageRecuDao;
import org.drmc.rasd.modele.MessageRecu;
import org.drmc.rasd.modele.ParametresApplication;
import org.drmc.rasd.service.ChargeurParametresApplication;
import org.drmc.rasd.service.IChargeurParametresApplication;
import org.drmc.rasd.service.fichiers.ConsommateurFichiers;
import org.drmc.rasd.service.fichiers.GestionFichiers;
import org.drmc.rasd.service.mockup.ChargeurParametresApplicationMockup;

/**
 *
 * @author RABBAH
 */
public class BaseMessagesRecusPanel extends javax.swing.JPanel {

    private final MainFrame parent;

    /**
     * Creates new form BaseMessagesRecusPanel
     */
    public BaseMessagesRecusPanel(MainFrame parent) {
        this.parent = parent;
        this.parent.setTitle("Base des messages reçus");
        initComponents();
        parent.getMenuPrincipal().setVisible(true);
        parent.getToolBarPrincipale().setVisible(true);
        myinit();
    }

    public BaseMessagesRecusPanel(MainFrame parent, Date dateMessage, String entete) {

        this.parent = parent;
        this.parent.setTitle("Base des messages transmis");
        initComponents();
        parent.getMenuPrincipal().setVisible(true);
        parent.getToolBarPrincipale().setVisible(true);
        myinit_date_entete(dateMessage, entete);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabMessages = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        entete1 = new javax.swing.JLabel();
        rechercherParNom1 = new javax.swing.JButton();
        jTextentete1 = new javax.swing.JTextField();
        dateMessages2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_JUMP_TO.png"))); // NOI18N
        jLabel1.setText("Base des messages reçus");

        tabMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabMessages.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabMessages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMessagesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabMessages);

        jTextField1.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtres de recherche"));

        entete1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        entete1.setText("Entête : ");

        rechercherParNom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/terp-stock_zoom.png"))); // NOI18N
        rechercherParNom1.setText("Rechercher");
        rechercherParNom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateMessages2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(entete1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTextentete1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rechercherParNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateMessages2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextentete1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(entete1)
                                .addComponent(rechercherParNom1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(452, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabMessagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMessagesMouseClicked
        this.jTextField1.setEnabled(true);

        String corps = (String) this.tabMessages.getValueAt(this.tabMessages.getSelectedRow(), 1);
        jTextField1.setText(corps);


    }//GEN-LAST:event_tabMessagesMouseClicked

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed

        String entete = this.jTextentete1.getText();
        Date date = this.dateMessages2.getDate();
        parent.setContentPane(new BaseMessagesRecusPanel(parent, date, entete));
        parent.pack();
        parent.setLocationRelativeTo(null);
        /* System.out.println("la ddddd "+date);
         java.sql.Date d = new java.sql.Date(date.getTime());
        
        
        
         if (!d.equals(null) && !entete.equals(null)) {
         System.out.println("recherche  "+d+entete);
         */
        /*} else if (!d.equals(null) && entete.equals(null)) {
         parent.setContentPane(new BaseMessagesRecusPanel(parent, d));
         parent.pack();
         setLocationRelativeTo(null);
         } else if (d.equals(null) && !entete.equals(null)) {
         parent.setContentPane(new BaseMessagesTransmisPanel(parent, entete));
         parent.pack();
         setLocationRelativeTo(null);
         } else {
         parent.setContentPane(new BaseMessagesTransmisPanel(parent));
         parent.pack();
         setLocationRelativeTo(null);
         }
         */
    }//GEN-LAST:event_rechercherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateMessages2;
    private javax.swing.JLabel entete1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextentete1;
    private javax.swing.JButton rechercherParNom1;
    private javax.swing.JTable tabMessages;
    // End of variables declaration//GEN-END:variables

    private void myinit() {

        try {
            IChargeurParametresApplication ca = new ChargeurParametresApplication();
            final ParametresApplication pa = ca.chargerParametres();
            IDbConnection dbConnection = DbConnection.getInstance(pa);
            IMessageRecuDao imrd = new MessageRecuDao(dbConnection);
            ModelMessageRecu mmr = new ModelMessageRecu(imrd.listeMessagesRecus());
            this.tabMessages.setModel(mmr);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ListeDesProfil.class.getName()).log(Level.SEVERE, null, ex);
        }

        /*
         List<MessageRecu> messagesRecus = new ArrayList();
         messagesRecus.add(new MessageRecu(1, "entete 1", "corps 1", new Date() , new Date(), ".a"));
         messagesRecus.add(new MessageRecu(2, "entete 1", "corps 2", new Date() , new Date(), ".a"));
         messagesRecus.add(new MessageRecu(3, "entete 1", "corps 3", new Date() , new Date(), ".a"));
         messagesRecus.add(new MessageRecu(4, "entete 1", "corps 4", new Date() , new Date(), ".a"));
         messagesRecus.add(new MessageRecu(5, "entete 2", "corps 5", new Date() , new Date(), ".a"));
         messagesRecus.add(new MessageRecu(6, "entete 2", "corps 6", new Date() , new Date(), ".a"));
         messagesRecus.add(new MessageRecu(7, "entete 2", "corps 7", new Date() , new Date(), ".a"));
         messagesRecus.add(new MessageRecu(8, "entete 2", "corps 8", new Date() , new Date(), ".a"));
         messagesRecus.add(new MessageRecu(9, "entete 2", "corps 9", new Date() , new Date(), ".a"));
         ModelMessageRecu mmr = new ModelMessageRecu(messagesRecus);
         this.tabMessages.setModel(mmr);                
         //MessageRecu messagesRecusSelectionner = messagesRecus.get(tabMessages.convertRowIndexToModel(tabMessages.getSelectedRow());)
         */
    }

    private void myinit_date_entete(Date dateMessage, String entete) {

        try {
            IChargeurParametresApplication ca = new ChargeurParametresApplication();
            final ParametresApplication pa = ca.chargerParametres();
            IDbConnection dbConnection = DbConnection.getInstance(pa);
            IMessageRecuDao imrd = new MessageRecuDao(dbConnection);
            ModelMessageRecu mmr = new ModelMessageRecu(imrd.listeMessagesRecuDateEntete(dateMessage, entete));
            this.tabMessages.setModel(mmr);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BaseMessagesTransmisPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
