/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.drmc.rasd.view;

import org.drmc.rasd.view.SaisieMessagePanel;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.drmc.rasd.controller.ModelMessageEnvoye;
import org.drmc.rasd.controller.ModelProfil;
import org.drmc.rasd.dao.DbConnection;
import org.drmc.rasd.dao.IDbConnection;
import org.drmc.rasd.dao.IMessageEnvoyeDao;
import org.drmc.rasd.dao.IProfilDao;
import org.drmc.rasd.dao.MessageEnvoyeDao;
import org.drmc.rasd.dao.ProfilDao;
import org.drmc.rasd.modele.MessageEnvoye;
import org.drmc.rasd.modele.ParametresApplication;
import org.drmc.rasd.service.ChargeurParametresApplication;
import org.drmc.rasd.service.IChargeurParametresApplication;
import org.drmc.rasd.service.communication.FtpManager;
import org.drmc.rasd.service.fichiers.IGestionFichiers;
import org.drmc.rasd.service.message.IGestionMessage;
import org.drmc.rasd.service.mockup.ChargeurParametresApplicationMockup;

/**
 *
 * @author RABBAH
 */
public class BaseMessagesTransmisPanel extends javax.swing.JPanel {

    private final MainFrame parent;

    /**
     * Creates new form BaseMessagesRecusPanel
     */
    public BaseMessagesTransmisPanel(MainFrame parent) {

        this.parent = parent;
        this.parent.setTitle("Base des messages transmis");
        initComponents();
        parent.getMenuPrincipal().setVisible(true);
        parent.getToolBarPrincipale().setVisible(true);
        myinit();

    }

    public BaseMessagesTransmisPanel(MainFrame parent, Date dateMessage) {

        this.parent = parent;
        this.parent.setTitle("Base des messages transmis");
        initComponents();
        parent.getMenuPrincipal().setVisible(true);
        parent.getToolBarPrincipale().setVisible(true);
        myinit_date(dateMessage);
    }

    public BaseMessagesTransmisPanel(MainFrame parent, Date dateMessage, String entete) {

        this.parent = parent;
        this.parent.setTitle("Base des messages transmis");
        initComponents();
        parent.getMenuPrincipal().setVisible(true);
        parent.getToolBarPrincipale().setVisible(true);

        myinit_date_entete(dateMessage, entete);
    }

    public BaseMessagesTransmisPanel(MainFrame parent, String entete) {
        this.parent = parent;
        this.parent.setTitle("Base des messages transmis");
        initComponents();
        myinit_entete(entete);
        parent.getMenuPrincipal().setVisible(true);
        parent.getToolBarPrincipale().setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        entete = new javax.swing.JLabel();
        rechercherParNom = new javax.swing.JButton();
        jTextentete = new javax.swing.JTextField();
        dateMessages1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabMessages = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        envoyer = new javax.swing.JButton();
        messageErreur = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_REDO.png"))); // NOI18N
        jLabel1.setText("Base des messages transmis");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtres de recherche"));

        entete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        entete.setText("Entête : ");

        rechercherParNom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/terp-stock_zoom.png"))); // NOI18N
        rechercherParNom.setText("Rechercher");
        rechercherParNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateMessages1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(entete, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextentete, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rechercherParNom, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateMessages1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextentete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(entete)
                                .addComponent(rechercherParNom)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabMessages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMessagesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabMessages);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        envoyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_GO_FORWARD.png"))); // NOI18N
        envoyer.setText("Re-envoyer");
        envoyer.setEnabled(false);
        envoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(envoyer)
                                .addGap(88, 88, 88)
                                .addComponent(messageErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(envoyer)
                    .addComponent(messageErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed

        String entete = this.jTextentete.getText();
        Date date = this.dateMessages1.getDate();        
        parent.setContentPane(new BaseMessagesTransmisPanel(parent, date, entete));
        parent.pack();
        parent.setLocationRelativeTo(null);

    }//GEN-LAST:event_rechercherActionPerformed

    private void tabMessagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMessagesMouseClicked
        this.jTextArea1.setEnabled(true);
        this.envoyer.setEnabled(true);

        String corps = (String) this.tabMessages.getValueAt(this.tabMessages.getSelectedRow(), 1);

        this.jTextArea1.setText(corps);

       
    }//GEN-LAST:event_tabMessagesMouseClicked

    private void envoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyerActionPerformed
        String messageAEnvoyer = jTextArea1.getText();
        if (parent.getGestionMessage().messageEstValide(messageAEnvoyer)) {
            String url = parent.getParametresApplication().getUrlFtp();
            String login = parent.getParametresApplication().getLoginFtp();
            String password = parent.getParametresApplication().getPasswordFtp();
            String prefixNomFichier = parent.getParametresApplication().getPrefixFichierEnvoye();
            String suffixNomFichier = parent.getParametresApplication().getSuffixFichierEnvoyer();
            int csn = parent.getCsn();
            SurveillancePanel sp = new SurveillancePanel(parent, messageAEnvoyer , parent.getCf());
            IMessageEnvoyeDao messageEnvoyeDao = parent.getMessageEnvoyeDao();
            IGestionMessage gestionMessage = parent.getGestionMessage();
            IGestionFichiers gestionFichier = parent.getGestionFichiers();
            FtpManager fm = new FtpManager(messageAEnvoyer, url, login,
                    password, prefixNomFichier, suffixNomFichier, csn, sp, messageEnvoyeDao, gestionMessage, gestionFichier, null, null);
            fm.start();
            parent.setContentPane(sp);
            parent.pack();
            parent.setLocationRelativeTo(null); //On centre la fenêtre sur l'écran
        } else {
            messageErreur.setText("Non respect du format du message");
        }


    }//GEN-LAST:event_envoyerActionPerformed
    /**/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateMessages1;
    private javax.swing.JLabel entete;
    private javax.swing.JButton envoyer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextentete;
    private javax.swing.JLabel messageErreur;
    private javax.swing.JButton rechercherParNom;
    private javax.swing.JTable tabMessages;
    // End of variables declaration//GEN-END:variables

    private void myinit() {
        try {
            IChargeurParametresApplication ca = new ChargeurParametresApplication();
            final ParametresApplication pa = ca.chargerParametres();
            IDbConnection dbConnection = DbConnection.getInstance(pa);
            IMessageEnvoyeDao imed = new MessageEnvoyeDao(dbConnection);
            ModelMessageEnvoye mme = new ModelMessageEnvoye(imed.listeMessagesEnvoyes());
            this.tabMessages.setModel(mme);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ListeDesProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void myinit_date(Date dateMessage) {

        try {
            IChargeurParametresApplication ca = new ChargeurParametresApplication();
            final ParametresApplication pa = ca.chargerParametres();
            IDbConnection dbConnection = DbConnection.getInstance(pa);
            IMessageEnvoyeDao imed = new MessageEnvoyeDao(dbConnection);
            ModelMessageEnvoye mme = new ModelMessageEnvoye(imed.listeMessagesEnvoyesDate(dateMessage));
            this.tabMessages.setModel(mme);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BaseMessagesTransmisPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void myinit_entete(String entete) {

        //String ent = entete;
        try {
            IChargeurParametresApplication ca = new ChargeurParametresApplication();
            final ParametresApplication pa = ca.chargerParametres();
            IDbConnection dbConnection = DbConnection.getInstance(pa);
            IMessageEnvoyeDao imed = new MessageEnvoyeDao(dbConnection);
            ModelMessageEnvoye mme = new ModelMessageEnvoye(imed.listeMessagesEnvoyesEntete(entete));
            this.tabMessages.setModel(mme);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BaseMessagesTransmisPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void myinit_date_entete(Date dateMessage, String entete) {

        try {
            IChargeurParametresApplication ca = new ChargeurParametresApplication();
            final ParametresApplication pa = ca.chargerParametres();
            IDbConnection dbConnection = DbConnection.getInstance(pa);
            IMessageEnvoyeDao imed = new MessageEnvoyeDao(dbConnection);
            ModelMessageEnvoye mme = new ModelMessageEnvoye(imed.listeMessagesEnvoyesDateEntete(dateMessage, entete));
            this.tabMessages.setModel(mme);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BaseMessagesTransmisPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    

}
