/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.drmc.rasd.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.drmc.rasd.controller.ModelProfil;
import org.drmc.rasd.dao.DbConnection;
import org.drmc.rasd.dao.IDbConnection;
import org.drmc.rasd.dao.IProfilDao;
import org.drmc.rasd.dao.ProfilDao;
import org.drmc.rasd.modele.ParametresApplication;
import org.drmc.rasd.modele.Profil;
import org.drmc.rasd.service.ChargeurParametresApplication;
import org.drmc.rasd.service.IChargeurParametresApplication;
import org.drmc.rasd.service.mockup.ChargeurParametresApplicationMockup;

/**
 *
 * @author usim
 */
public class ListeDesProfil extends javax.swing.JPanel {

    /**
     * Creates new form ListeDesProfil
     */
    private final MainFrame parent;

    /**
     * Creates new form SaisieMessagePanel
     *
     * @param parent
     */
    /**
     * public ListeDesProfil(MainFrame parent, String s) { this.parent = parent;
     * jLabel1.setText(s); this.parent.setTitle("Liste des profiles");
     * initComponents(); parent.getMenuPrincipal().setVisible(true);
     * parent.getToolBarPrincipale().setVisible(true); myinit(); }
     */
    public ListeDesProfil(MainFrame parent, String s) {
        this.parent = parent;
        this.parent.setTitle("Gestion des profiles");
        initComponents();
        parent.getMenuPrincipal().setVisible(true);
        parent.getToolBarPrincipale().setVisible(true);
        myinit();
        jLabel1.setText(s);
    }

    public ListeDesProfil(MainFrame parent) {
        this.parent = parent;
        this.parent.setTitle("Gestion des profiles");
        initComponents();
        parent.getMenuPrincipal().setVisible(true);
        parent.getToolBarPrincipale().setVisible(true);
        myinit();
    }

    ListeDesProfil(CréationDesComptes aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ajouter = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(supprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        parent.setContentPane(new CréationDesComptes(parent));
        parent.pack();
        parent.setLocationRelativeTo(null);
    }//GEN-LAST:event_ajouterActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed

        int i = -1;
        i = jTable1.getSelectedRow();


        try {
            IChargeurParametresApplication ca = new ChargeurParametresApplication();
            final ParametresApplication pa = ca.chargerParametres();
            //final IGestionMessage gestionMessage = new GestionMessage();

            IDbConnection dbConnection = DbConnection.getInstance(pa);
            if (i != -1) {
                int id = (int) jTable1.getValueAt(i, 0);
                Profil p = new Profil(id, null, null, null);
                IProfilDao ipd = new ProfilDao(dbConnection);
                ipd.supprimer(p);
                this.myinit();
            } else {
                jLabel1.setText("tu dois selectionner un profil");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListeDesProfil.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ListeDesProfil.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_supprimerActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables

    private void myinit() {
        try {
            IChargeurParametresApplication ca = new ChargeurParametresApplication();
            final ParametresApplication pa = ca.chargerParametres();
            IDbConnection dbConnection = DbConnection.getInstance(pa);
            IProfilDao ipd = new ProfilDao(dbConnection);
            ModelProfil mp = new ModelProfil(ipd.listeProfils());
            this.jTable1.setModel(mp);




        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ListeDesProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
