/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.drmc.rasd.view;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JToolBar;
import org.drmc.rasd.dao.IMessageEnvoyeDao;
import org.drmc.rasd.dao.IMessageRecuDao;
import org.drmc.rasd.dao.IProfilDao;
import org.drmc.rasd.modele.ParametresApplication;
import org.drmc.rasd.service.fichiers.ConsommateurFichiers;
import org.drmc.rasd.service.fichiers.IGestionFichiers;
import org.drmc.rasd.service.message.IGestionMessage;

/**
 *
 * @author RABBAH
 */
public class MainFrame extends javax.swing.JFrame {

    private ParametresApplication parametresApplication;
    private IGestionMessage gestionMessage;
    private IMessageEnvoyeDao messageEnvoyeDao;
    private IGestionFichiers gestionFichiers;
    private IProfilDao profilDao;
    private int csn = 1;
    private IMessageRecuDao messageRecuDao;
    private ConsommateurFichiers cf;
//    /**
//     * Creates new form MainFrame
//     */
//    public MainFrame() {
//        initComponents();
//        setLocationRelativeTo(null); //On centre la fenêtre sur l'écran
//        setIcon();        
//    }

    public MainFrame(ParametresApplication pa, IGestionMessage gestionMessage, IMessageEnvoyeDao messageEnvoyeDao, IGestionFichiers gestionFichiers,
            IProfilDao profilDao, IMessageRecuDao messageRecuDao, ConsommateurFichiers cf) {
        this.parametresApplication = pa;
        this.gestionMessage = gestionMessage;
        this.messageEnvoyeDao = messageEnvoyeDao;
        this.gestionFichiers = gestionFichiers;
        this.profilDao = profilDao;
        this.messageRecuDao = messageRecuDao;
        this.cf = cf;
        initComponents();
        
       
        setLocationRelativeTo(null); //On centre la fenêtre sur l'écran
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBarPrincipale = new javax.swing.JToolBar();
        saisireMessageButton = new javax.swing.JButton();
        sureveillanceButton = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        seDeconnecter = new javax.swing.JMenuItem();
        quitter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        saisireMessage = new javax.swing.JMenuItem();
        baseMessagesRecus = new javax.swing.JMenuItem();
        baseMessagesEnvoyes = new javax.swing.JMenuItem();
        sureveillanceMessages = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        maintenance = new javax.swing.JMenuItem();
        listeDesProfiles = new javax.swing.JMenuItem();
        gestionModele = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        aide = new javax.swing.JMenuItem();
        apropos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));
        setResizable(false);

        toolBarPrincipale.setRollover(true);

        saisireMessageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_ADD.png"))); // NOI18N
        saisireMessageButton.setToolTipText("Ecrire un message");
        saisireMessageButton.setFocusable(false);
        saisireMessageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saisireMessageButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarPrincipale.add(saisireMessageButton);

        sureveillanceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_NETWORK.png"))); // NOI18N
        sureveillanceButton.setToolTipText("Surveillance des messages");
        sureveillanceButton.setFocusable(false);
        sureveillanceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sureveillanceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarPrincipale.add(sureveillanceButton);

        menuPrincipal.setToolTipText("");
        menuPrincipal.setName(""); // NOI18N

        jMenu1.setText("Fichier");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        seDeconnecter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        seDeconnecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_DISCONNECT.png"))); // NOI18N
        seDeconnecter.setText("Se déconnecter");
        seDeconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seDeconnecterActionPerformed(evt);
            }
        });
        jMenu1.add(seDeconnecter);

        quitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_QUIT.png"))); // NOI18N
        quitter.setText("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        jMenu1.add(quitter);

        menuPrincipal.add(jMenu1);

        jMenu2.setText("Gestion des messages");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        saisireMessage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saisireMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_ADD.png"))); // NOI18N
        saisireMessage.setText("Saisir message");
        saisireMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisireMessageActionPerformed(evt);
            }
        });
        jMenu2.add(saisireMessage);

        baseMessagesRecus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        baseMessagesRecus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_GOTO_BOTTOM.png"))); // NOI18N
        baseMessagesRecus.setText("Base messages reçus");
        baseMessagesRecus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseMessagesRecusActionPerformed(evt);
            }
        });
        jMenu2.add(baseMessagesRecus);

        baseMessagesEnvoyes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        baseMessagesEnvoyes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_REDO.png"))); // NOI18N
        baseMessagesEnvoyes.setText("Base messages envoyés");
        baseMessagesEnvoyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseMessagesEnvoyesActionPerformed(evt);
            }
        });
        jMenu2.add(baseMessagesEnvoyes);

        sureveillanceMessages.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        sureveillanceMessages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_NETWORK.png"))); // NOI18N
        sureveillanceMessages.setText("Surveillance des messages");
        sureveillanceMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sureveillanceMessagesActionPerformed(evt);
            }
        });
        jMenu2.add(sureveillanceMessages);

        menuPrincipal.add(jMenu2);

        jMenu3.setText("Administration");

        maintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_EXECUTE.png"))); // NOI18N
        maintenance.setText("Maintenance");
        maintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceActionPerformed(evt);
            }
        });
        jMenu3.add(maintenance);

        listeDesProfiles.setText("Gestion des profiles");
        listeDesProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeDesProfilesActionPerformed(evt);
            }
        });
        jMenu3.add(listeDesProfiles);

        gestionModele.setText("Gestion des modeles de messages");
        gestionModele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionModeleActionPerformed(evt);
            }
        });
        jMenu3.add(gestionModele);

        jMenuItem1.setText("Configuration");
        jMenu3.add(jMenuItem1);

        menuPrincipal.add(jMenu3);

        jMenu4.setText("?");

        aide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_DIALOG_INFO.png"))); // NOI18N
        aide.setText("Aide");
        jMenu4.add(aide);

        apropos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/drmc/rasd/images/icons/STOCK_ABOUT.png"))); // NOI18N
        apropos.setText("Apropos");
        apropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aproposActionPerformed(evt);
            }
        });
        jMenu4.add(apropos);

        menuPrincipal.add(jMenu4);

        setJMenuBar(menuPrincipal);
        menuPrincipal.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 127, Short.MAX_VALUE)
                .addComponent(toolBarPrincipale, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBarPrincipale, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saisireMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisireMessageActionPerformed
        this.setContentPane(new SaisieMessagePanel(this));
        this.pack();
        setLocationRelativeTo(null); //On centre la fenêtre sur l'écran
    }//GEN-LAST:event_saisireMessageActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        this.fermerFenetre();
    }//GEN-LAST:event_quitterActionPerformed

    private void seDeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seDeconnecterActionPerformed
        this.setContentPane(new AuthentificationPanel(this));
        this.pack();
    }//GEN-LAST:event_seDeconnecterActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void baseMessagesRecusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseMessagesRecusActionPerformed
        this.setContentPane(new BaseMessagesRecusPanel(this));
        this.pack();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_baseMessagesRecusActionPerformed

    private void baseMessagesEnvoyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseMessagesEnvoyesActionPerformed
        this.setContentPane(new BaseMessagesTransmisPanel(this));
        this.pack();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_baseMessagesEnvoyesActionPerformed

    private void sureveillanceMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sureveillanceMessagesActionPerformed
        this.setContentPane(new SurveillancePanel(this, null, cf));
        this.pack();
      

        setLocationRelativeTo(this);
        
    }//GEN-LAST:event_sureveillanceMessagesActionPerformed

    private void maintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceActionPerformed
        this.setContentPane(new MaintenancePanel(this));
        this.pack();
        setLocationRelativeTo(this);
    }//GEN-LAST:event_maintenanceActionPerformed

    private void aproposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aproposActionPerformed
        this.setContentPane(new Aproposs(this));
        this.pack();
        setLocationRelativeTo(this);
    }//GEN-LAST:event_aproposActionPerformed

    private void listeDesProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeDesProfilesActionPerformed
        this.setContentPane(new ListeDesProfil(this));
        this.pack();
        setLocationRelativeTo(this);
    }//GEN-LAST:event_listeDesProfilesActionPerformed

    private void gestionModeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionModeleActionPerformed
       this.setContentPane(new GestionModelesMessages(this));
        this.pack();
        setLocationRelativeTo(this);
    }//GEN-LAST:event_gestionModeleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                MainFrame mf = new MainFrame();
//                mf.setContentPane(new BaseMessagesRecusPanel(mf));
//                mf.pack();
//                mf.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aide;
    private javax.swing.JMenuItem apropos;
    private javax.swing.JMenuItem baseMessagesEnvoyes;
    private javax.swing.JMenuItem baseMessagesRecus;
    private javax.swing.JMenuItem gestionModele;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listeDesProfiles;
    private javax.swing.JMenuItem maintenance;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem quitter;
    private javax.swing.JMenuItem saisireMessage;
    private javax.swing.JButton saisireMessageButton;
    private javax.swing.JMenuItem seDeconnecter;
    private javax.swing.JButton sureveillanceButton;
    private javax.swing.JMenuItem sureveillanceMessages;
    private javax.swing.JToolBar toolBarPrincipale;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/org/drmc/rasd/images/Logo_Meteo_Maroc.jpg")));
    }

    private void fermerFenetre() {
        WindowEvent evenementFermeture = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(evenementFermeture);
    }

    public JMenuBar getMenuPrincipal() {
        return menuPrincipal;
    }

    public JMenu getJMenu3() {
        return jMenu3;
    }

    public JToolBar getToolBarPrincipale() {
        return toolBarPrincipale;
    }

    public ParametresApplication getParametresApplication() {
        return parametresApplication;
    }

    public IGestionMessage getGestionMessage() {
        return gestionMessage;
    }

    public IMessageEnvoyeDao getMessageEnvoyeDao() {
        return messageEnvoyeDao;
    }

    public IProfilDao getProfilDao() {
        return profilDao;
    }

    public int getCsn() {
        return csn++;
    }

    public IGestionFichiers getGestionFichiers() {
        return gestionFichiers;
    }

    public IMessageRecuDao getMessageRecuDao() {
        return messageRecuDao;
    }

    public ConsommateurFichiers getCf() {
        return cf;
    }

    
}
